version: '3.8'

services:
  mysql:
    build:
      context: ./application/mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/volume:/var/lib/mysql
    networks:
      - picpay

  redis:
    build:
      context: ./application/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - ./redis/volume:/data
    networks:
      - picpay

  app:
    build:
      context: ./application
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    depends_on:
      - redis
      - mysql
    networks:
      - picpay

networks:
  picpay:
    driver: bridge
